<template lang="pug">
  .email-notification
    p You have received a new order:

    //- From
    //- For
    //- Agency
    //- Estimate
    //- Start Date
    //- End Date
    //- Total
    //- Spots
    //- Station

    p This is an automated message generated by the Videa Order Management System.
    p If you need assistance, please contact Videa Customer Cart at: opsnotification@videa.tv

</template>

<script>
  import moment from 'moment'

  export default {
    data () {
      return {
        from: 'Videa',
        datetimePulled: null,
        buyer: {
          name: '',
          email: ''
        },
        agency: null,
        advertiser: null,
        product: null,
        flightStartDate: null,
        flightEndDate: null,
        targetDemo: 'P35-64',
        totalTrps: 0,
        budget: 0,
        daypartsRequested: []
      }
    },
    computed: {
      subject () {
        return `[${this.station}] - New Avails were pulled for ${this.advertiser} for ${this.budget} starting ${this.flightStartDate}`

      }
    }
  }
</script>
