<template lang="pug">
  .email-notification
    p Order No {{}} has been accepted and confirmed. Attached are the R100 files and the order PDF. Please add to your traffic system.

    //- From
    //- For
    //- Agency
    //- Estimate
    //- Start Date
    //- End Date
    //- Total
    //- Spots
    //- Station

    p Please click here to review the order.

    p This is an automated message generated by the Videa Order Management System.
    p If you need assistance, please contact Videa Customer Cart at: opsnotification@videa.tv

</template>

<script>
  import moment from 'moment'

  export default {
    data () {
      return {
        from: 'Videa',
        datetimePulled: null,
        buyer: {
          name: '',
          email: ''
        },
        agency: null,
        advertiser: null,
        product: null,
        flightStartDate: null,
        flightEndDate: null,
        targetDemo: 'P35-64',
        totalTrps: 0,
        budget: 0,
        daypartsRequested: []
      }
    },
    computed: {
      subject () {
        return `[${this.station}] - Confirmed New Order No ${this.orderId} from Videa for ${this.advertiser} for ${this.total} starting ${this.startDate}`

      }
    }
  }
</script>
