<template lang="pug">
  .page.terms.vui-container--medium.vui-p-top--large
    vui-title Videa Platform Terms of Use Agreement
    p
      strong
        | EACH USER SHOULD CAREFULLY READ THE FOLLOWING TERMS OF USE AGREEMENT (THE "AGREEMENT") BEFORE ACCESSING OR USING THE VIDEA PLATFORM OR THE VIDEA SERVICE. USER MAY NOT ACCESS OR USE THIS SERVICE WITHOUT FIRST AGREEING TO THESE TERMS. BY CHECKING THE "I ACCEPT" BOX OR OTHERWISE BY ACCESSING OR USING THE VIDEA SERVICE, USER AGREES TO ACCEPT ALL OF THESE TERMS FOR ITSELF AND THE CUSTOMER ON BEHALF OF WHICH USER IS USING THE VIDEA SERVICE.USER HEREBY REPRESENTS THAT USER IS AUTHORIZED TO ACCEPT THESE TERMS AND CONDITIONS ON BEHALF OF SUCH CUSTOMER.
    p
      | Videa, LLC ("Videa") and User (as defined below) are entering into this Agreement pursuant to which Videa will provide Users with access to Videa Platform (as defined below) and the services and information provided through the Videa Platform (the “Videa Service”), subject to the terms of the applicable Customer agreement and the terms and conditions set forth herein.
    p
      strong Definitions:
    p
      | "Advertising Agency Customer" means an advertiser, an advertising agency that uses the Videa Platform and Videa Service to view pricing, availability and other information about and to purchase advertising avails from broadcast television stations that make their advertising inventory available via the Videa Platform.
    p
      | "Station Customer" means a broadcast television station or station group or an advertising rep network working with a station or station group that uses the Videa Platform and Videa Service as a channel through which to manage and sell advertising inventory within its television programming.
    p
      | "Advertising Agency User" means a User that is an employee of an Advertising Agency Customer.
    p
      | "Effective Date" means the date the Customer and/or User begins using the Videa Service.
    p "Station User" means a User that is an employee of a Station Customer.
    p
      | "Customer" means any Customer that uses the Videa Service and Videa Platform, including both Station Customers and Advertising Customers.
    p
      | "User" means any person using the Videa Platform and Videa Service on behalf of a Customer and the term, as used in this Agreement, shall mean both Station User and Advertising Agency User.
    p
    ol
      li
        p
          u The Videa Service/Other Agreements.
          |  The Videa Platform and the Videa Service facilitate the programmatic purchase and sale of television advertising inventory by providing tools and pricing and inventory transparency that collectively enable Advertising Agency Customers to maximize their investment in advertising space and that enable Station Customers to enjoy yield optimization, combine inventory for scale and maximize their advertising sales capability.In addition to this Agreement, Customers' and Users' use of the Videa Platform and the Videa Services is subject to the Videa Privacy Policy, which is posted on the Videa website.This Agreement is in addition to any agreement entered by and between a Customer and Videa. In the event of a conflict between this Agreement and such Customer agreement, the Customer agreement will govern. The specific attributes and other business terms applicable to User's use of the Videa Services and the Videa Platform are set forth in the applicable Customer agreement.
      li
        p
          u Licenses to Videa Platform/Restrictions.
          |  Subject to the terms of this Agreement, Videa grants to User a non-exclusive, revocable, non-transferable, non-sublicensable, limited right and license, during the Term of this Agreement, to access and use the Videa Service and Videa Platform solely on behalf of and for the internal business needs of the Customer through which User's access is authorized and subject to the use description set forth in the ordering document.
        p
          | User agrees that User will not, directly or indirectly, (i) modify, adapt, reverse engineer, disassemble, de-compile or otherwise derive source code from the Videa Platform or Videa Services (ii) create derivative works based on the Videa Platform and Videa Services; (iii) make unauthorized copies of the Videa Platform or Videa Services; (iv) transfer the Videa Platform or Videa Services or any part thereof to any third party without the prior written consent of Videa; (v) resell the Videa Platform or Videa Services; or (vi) use the Videa Platform or the Videa Service for the benefit of any person or entity other than the Customer through which User's access is authorized. User agrees that it will not remove, alter, cover or obfuscate any copyright notices, logo or other proprietary rights notices or proprietary mark placed or embedded by Videa or in the Videa Platform or Videa Services.
      li
        p
          u Usage, Obligations and Availability – Generally
          | User is responsible for maintaining the security and confidentiality of the Videa account of the Customer through which User's access is authorized.To that end, User will maintain the confidentiality of its assigned account ID and/or User ID(s) for the Videa Services and Videa Platform, as well as all assigned or created usernames and passwords, etc. (collectively referred to as Security Devices) used to access the Videa Services and Videa Platform. User will not provide access to the Videa Services or the Videa Platform to any third party. Further, User will not provide its Security Devices or its Videa Platform access rights to any other individual. User acknowledges and agrees that User (and the Customer through which User's access is authorized) are by any actions, and responsible for all activities and charges incurred under User's Account ID or User ID(s) or taken through use of Security Devices issued to User or created by User, whether or not such actions were authorized by User or the applicable Customer. User may not share its username or password with any other employees of the Customer. User agrees to notify Videa immediately if User believes User's Security Devices have been lost, stolen or used without authorization. "Unauthorized use" includes not only use of the Videa Services and the Videa Platform by someone other than User, but use of the Videa Services and Videa Platform outside of the scope of this Agreement or the specific permissions granted to the applicable Customer and/or User under this Agreement or an applicable Customer agreement.
        p
          | User understands and agrees that Videa may use a combination of cookies (to facilitate the recognition of Customer's device) and two-factor authentication to verify Customer's identity and access authorizations.
        p
          | The Videa Service makes available different areas of the Videa Platform to Advertising Agency Users and Station Users, based on the permissions granted to each applicable Advertising Agency Customer or Station Customer (as described in the applicable Customer ordering document). The Videa Platform is designed to restrict Advertising Agency Users to the Advertising Agency section of the Videa Platform and Station Users to the section of the Videa Platform that relates to the specific Station Customer's advertising inventory, reports and other information.For clarity, each Station Customer and its Users shall be limited to viewing the materials directly correlated to its station (or station group) and shall not be granted permission to view other Station Customer's data. User will not access or attempt to access any portions of the Videa Platform that it is not expressly authorized to access.Should the User view or attain any material not intended for that particular User, that User shall immediately destroy such material.
        p
          | If User is providing administrative services on behalf of a Customer ("Customer Administrator"), Customer Administrator shall make sure that each of the applicable Customer's Users is registered with Videa and has a distinct password and username to access the Videa Platform. Should any registered User no longer be employed by the Customer, the Customer Administrator shall promptly notify Videa and Videa will deactivate the User's username and password. Failure to do so shall be considered a breach of this Agreement and may result in Customer's total loss of the Videa Platform and Videa Services.
        p
          | User represents and warrants that User will use the Videa Service and Videa Platform only for lawful purposes and for the purposes contemplated by this Agreement, including any and all Platform Limitations. User agrees and understands that the use of the Videa Service and Videa Platform for any purpose that is unlawful or in any manner that could damage, disable, overburden or impair the operation of Videa's Platform, Videa's computer systems or networks or any other party's use of the Videa Service or Platform, is strictly prohibited. User shall not use any device, software, routine, or robotics that interferes with, or attempts to interfere with the normal operation of the Videa Service or Videa Platform.Further, User shall not engage in or permit any third party to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Videa Platform or the Videa Service in any medium, including without limitation by any automated or non-automated "scraping"; (ii) using any automated system, including without limitation "robots," "spiders," "offline readers," etc., to access the Videa Platform or the Videa Service in a manner that sends more request messages to the service providers' servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser; (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Videa Service; (v) uploading invalid data, viruses, worms, or other software agents through the Videa Platform or the Videa Service; (vi) impersonating another person or otherwise misrepresenting User's affiliation with a person or entity (including any Videa Customer other than the Customer through which User's access to the Videa Platform is authorized), conducting fraud, hiding or attempting to hide User's identity; or (vii) bypassing the measures Videa may use to prevent or restrict access to portions of the Videa Platform and Videa Services.
        p
          | Without limiting the foregoing, User shall not attempt, by any means, to gain access to data or information that User are not legally entitled to access, as described in more detail above. User shall not use the Videa Service and Videa Platform to commit fraud, price fixing or otherwise engage in illegal activity.User agrees and acknowledges that much of the information provided in the Videa Platform and Videa Service comes from third party providers and Videa cannot represent, warrant or guaranty the accuracy of such third party information. Videa has the right, but not the obligation, to monitor the use of the Videa Service by all Users and reserves the right to suspend, limit access and/or terminate the account of any participant that violates the terms of this Agreement.
        p
          | User understands and agrees that each Customer must provide at such Customer's own expense all necessary Internet connections, computers and other equipment needed to access the Videa Platform utilize the Videa Service.User and the applicable Customer shall be solely responsible for all security related to these connections and devices.The availability of the Videa Platform and Videa Service may be subject to interruption and delay due to causes beyond Videa's reasonable control, including any malfunction related to User's equipment.
      li
        p
          u Ownership/Proprietary Rights.
          |  Nothing in this Agreement will cause or result in a transfer of copyright, trademark or other rights in the Videa Platform or the Videa Service from Videa to a Customer or a User, and Videa will retain any rights of copyright, trademark and any other intellectual property rights that Videa possessed prior to providing the Customer and/or User access to the Videa Platform and the Videa Service or that Videa develops during the term of this Agreement (the "Videa Property Rights"), subject only to the limited license granted to Customer and User to use the Videa Platform and the Videa Service as described in this Agreement.  Further, any input, feedback or suggestions regarding the features, functionality, usability or other aspects of the Videa Platform or the Videa Service that User provides to Videa ("Feedback") is provided as-is and without charge.User assigns to Videa all rights in and to the Feedback and Videa owns and may make, use modify, distribute, and otherwise commercialize the Feedback as part of the Videa Service, the Videa Platform or any other Videa product or service offering.If for any reason Customer's assignment of the Feedback is ineffective, User hereby grants and agrees to grant to Videa a non-exclusive, perpetual, irrevocable, royalty free, worldwide right and license to use, reproduce, disclose, sublicense, distribute, modify and otherwise exploit such Feedback without restriction.
        p
          | Nothing in this Agreement will cause or result in a transfer of copyright, trademark or other rights in any software, hardware, content, or data maintained by the Customer through which User is authorized to access the Videa Platform or any confidential information (the "Customer Data"), and the applicable Customer shall retain any rights of copyright, trademark and any other intellectual property rights in the Customer Data (the "Customer Property Rights") that Customer possessed prior to the Effective Date of this Agreement, subject only to the limited right to Videa to use the Customer Data in connection with the Videa Services.
      li
        p
          u Confidentiality.
          |  User acknowledges that the Videa Platform and the Videa Service each is confidential to Videa. Videa acknowledges that the Customer Data may contain information and material confidential to Customer. The term
          b "confidential"
          |  means non-public information or material concerning a party's (i) current, future, or proposed products, services, site features and/or tools; (ii) purchasing, accounting or marketing activity, including marketing plans, sales data, business methods, unpublished promotional materials, costs and pricing, and/or customer lists; (iii) backend administrative products or services, or access to a party's online products and/or systems; and/or (iv) source code, file formats, file layouts, processes, procedures and other backend/administrative controls. The term "confidential" does not apply to information or material that the receiving party can demonstrate (a) is or becomes generally known or available through no fault of the non-disclosing party; (b) is known by a party prior to the time of disclosure and is not subject to restriction; (c) is independently developed or learned by a party other than pursuant to this Agreement; or (d) is lawfully obtained from a third party who has the right to make such disclosure without restriction. If a party is required by law to disclose confidential information or material of the other, it will provide the other party with reasonable notice and an opportunity to obtain a protective order, if possible, prior to disclosing the information or material. Except with respect to trade secrets disclosed by a party under this Agreement, the confidentiality obligations of each party with respect to the other party's confidential information shall expire two (2) years following the disclosure of such confidential information.
        p
          | Videa may provide User with the ability to export certain data and reports from the Videa Platform. The provision of such export capabilities does not, in any way, affect the confidential status of confidential information that is exported or printed to hard copy.
      li
        p
          u Lost Security Devices.
          |  If User believes that his/her User Security Devices have been lost or stolen, or that someone is using User’s Account IDs or Customer IDs, User shall notify Videa immediately.  Further, if User’s unauthorized use of the Videa Service or Videa Platform causes Videa to be in violation of any agreement between Videa and any third party information provider, User and the applicable Customer shall indemnify and hold harmless Videa for any such violation and Videa has the right to immediately terminate or restrict both User’s and/or such Customer’s access to the Videa Platform and Videa Services.
      li
        p
          u Electronic Communication/Signatures.
          |  User agrees to receive any and all disclosures and/or written notices required by applicable law and regulation and all other communications electronically by e-mail or within the Videa Platform and Videa Service. Although Videa reserves the right to provide communications and notices in paper format at any time, User agrees Videa is under no obligation to do so. User also agrees that Videa may respond to User with an e-mail to any communication User sends to Videa, regardless of whether User's original communication to us was an e-mail. User agrees that instructions authorized using the Videa Platform and Videa Service shall be deemed to be in "writing" and to have been "signed" for all purposes and that any electronic record of any such transaction or instruction will be deemed to be in writing. User will not contest the legally binding nature, validity, or enforceability of any such transactions or instructions initiated or executed through the Videa Platform and Videa Service based on the fact that it was entered and executed electronically, and expressly waive any and all rights to assert such a claim.
      li
        p
          u Notices.
          |  Except as otherwise provided herein, all notices to be given to either party under this Agreement will be deemed given upon receipt and may be given by hand delivery, certified mail (return receipt requested), overnight courier service, or facsimile (so long as such facsimile is followed up by mail) to the parties at the addresses set forth in the Customer's ordering document.
      li
        p
          u Term and Termination.
          |  This Agreement will take effect on the Effective Date and will continue for so long as the applicable Customer agreement remains in effect (unless the User's access is terminated earlier).User's rights to access the Videa Platform and the Videa Services will terminate (a) if User violates any of the terms of this Agreement; (b) if User's employment or authorization status with a Customer changes or is terminated; or (c) if Videa ceases to provide the Videa Platform or the Videa Services. Videa may also terminate this Agreement for convenience at any time.Videa will have no liability to User for any termination of this Agreement or of User's rights to access the Videa Platform or the Videa Services. Those terms that, by their nature, are intended to be performed after the expiration or termination of this Agreement will survive such termination or expiration.
      li
        p
          u Disclaimer of Warranty.
          |  USER EXPRESSLY AGREES THAT USER'S USE OF THE VIDEA PLATFORM AND THE VIDEA SERVICE IS AT USER'S SOLE RISK, AND THAT THE VIDEA SERVICES, THE VIDEA PLATFORM ARE PROVIDED "AS IS" WITH NO WARRANTIES WHATSOEVER. VIDEA FURTHER DISLCAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, WHETHER ORAL OR WRITTEN WITH RESPECT TO THE VIDEA PLATFORM AND VIDEA SERVICE, INCLUDING, WITHOUT LIMITATION, NON-INFRINGEMENT, OR ANY IMPLIED WARRANTIES OF AVAILABILITY, RELIABILITY, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
      li
        p
          u Indemnification.
          |  User agrees to defend, indemnify and hold Videa, and Videa's officers, directors, shareholders, employees and representatives harmless from and against any third party claims, including any damages, costs, expenses and attorneys' fees arising out of this Agreement and/or Users use of the Videa Platform and/or Videa Services.
      li
        p
          u Limitation of Liability.
          |  IN NO EVENT WILL VIDEA BE RESPONSIBLE TO USER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING LOST PROFITS (EVEN IF ADVISED OF THE POSSIBILITY THEREOF) ARISING IN ANY WAY OUT OF YOUR PARTICIPATION IN THE VIDEA SERVICE OR THE VIDEA PLATFORM,VIDEA'S TOTAL, AGGREGATE LIABLITY TO YOU IS LIMITED TO $1,000.
      li
        p
          u Governing Law.
          |  This Agreement and User's use of the Videa Platform and the Videa Services will be governed by the laws of the State of New York, excluding its conflicts of laws rules.
      li
        p
          u General Terms.
          |  No delay or omission by Videa to exercise any right or power accruing upon any non-compliance or default by Customer with respect to any of the terms of this Agreement shall impair any such right or power or be construed to be a waiver thereof. A waiver by Videa of any of the covenants, conditions, or agreements to be performed by Customer shall not be construed to be a waiver of any succeeding breach thereof or of any other covenant, condition or agreement herein contained. The availability of Videa Platform and Videa Services are subject to interruption and delay due to causes beyond Videa's control. Videa will be excused hereunder, and shall not be liable for any period it is prevented from performing any services or obligations pursuant hereto in whole or in part as a result of causes beyond its reasonable control, including but not limited to an act of God;  or an act of a public enemy; acts of the United States or any state or political subdivision; war; civil disturbance; court order; labor dispute, fires, severe weather, floods, earthquakes, natural disasters mechanical equipment failure, or other occasional cause beyond its control to include shortages, telecommunications or Internet outages, fluctuations, and/or interruptions in electrical power, heat, light or air conditioning, and such non-performance shall not be a ground for termination.  Neither this Agreement nor any portion hereof shall be assigned, sublicensed or otherwise transferred by User without Videa's prior written consent.  If any provision of this Agreement is unenforceable, the validity and enforceability of the other provisions shall not be affected. The parties agree that communications relating to the Agreement sent via e-mail constitute a "writing" for all purposes, including the giving of notice, hereunder. The parties agree that all transactions that occur under this Agreement occur, or shall be deemed to occur in the United States of America.
      li
        p
          u Changes to the Videa Service and the Agreement.
          |  Videa reserves the right to suspend or change the Videa Services and the Videa Platform and this Agreement, including the fees charged for the Videa Services and the areas of access to the Videa Platform, in Videa's sole discretion from time to time, by either sending User notice of such changes or posting such changes within the Videa Platform.If User does not agree to any amendments, User's sole and exclusive remedy is to stop using the Videa Platform and Videa Services. User's continued use of the Videa Services after Customer is notified of any change will constitute User's acceptance of and agreement to be bound by the change.
</template>

<script>
  export default {
    name: 'terms',

    metaInfo: {
      title: 'Terms of Use',
    },

    beforeCreate () {
      this.$store.state.activeApp = null
    }
  }
</script>
