accept_all_buyer_ratings_except_zeros:
accept_button:
accepted_by_agency:
accepted_by_station:
add_a_week_button:
add_offer_button:
add_programs_link:
advertiser:
advertisername:
agency:
agency_name:
agency_notes:
agency_order_id:
agency_order_number:
agency_status:
agencyname:
air_date:
air_time:
all_offers:
all_order_preempts:
aur:
aur_last_year:
aur_this_year:
avail_number:
availed_cpp:
availed_rate:
availed_rating:
avg_cpp:
bonus:
buyer:
buyer_comment:
buyer_imp:
buyer_name:
buyer_need_goal:
buyer_need_high:
buyer_need_low:
buyer_order_comment:
buyer_rating:
campaign_delivery_percent:
campaign_name:
cancel_button:
classification:
clear_button:
client:
columns:
copy_offer_button:
cpe:

cpp:
cpp_goal:
create_mgs:
credit:
currency:
current_hh_grps_impressions:
current_hh_grps_imps:
current_information:
current_ratings_impressions:
current_rtgs_imps:
customer_care_comment_to_station:
customer_care_internal_notes:
date_offer_sent:
date_time_order_completed:
daypart:
days:
deal_type:
delete_offer_button:
delete_spots_button:
demo:
difference:
dollars:
draft:
draft_and_pending_orders_only:
draft_mg:
due_date:
edit_avail_button:
edit_buyer_specs_and_daypart_goals:
edit_offer_button:
end:
end_date:
estimate:
estimate_id:
estimate_no:
estimate_number:
exclude_zero_spots:
expiration_date:
export_to_excel:
flight_end:
flight_end_date:
flight_start:
flight_start_date:
gdlns:
gross_market_budget:
grps:
grps_goal:
guidelines_button:
guidelines_warnings_violations:
hiatus_weeks:
intended_air_date:
last_updated:
last_updated_by:
len:
length:
line_$_total:
line_number:
line_type:
location:
makegood:
makegood_comment:
makegood_comments:
makegood_due:
makegood_number:
makegood_sent:
makegood_status:
makegood_total:
makegood_type:
manage_schedule:
manage_schedule_link:
market_budget:
market_competitive_high_cpp:
market_competitive_low_cpp:
metered:
metric:
mg_preempts:
mg_spots:
mg_transfers:
missed_only:
missed_spots:
missed_value:
mix_goal:
no_of_spots:
offer:
offer_number:
offer_status:
offer_type:
offer_version:
on_the_books_max_rate:
on_the_books_min_rate:
open_preempt_note:
open_preempts:
order:
order_completed:
order_completed_by:
order_count:
order_date:
order_id:
order_no:
order_v_missed:
order_v_traffic:
order_value:
ordered_spots:
pending_mg:
pending_mgs:
preempt_reason:
primary_demo:
product:
program:
program_change:
purchased_grps_impressions_to_date:
purchased_grps_imps_to_date:
quarter:
rate:
rating:
redeliver_button:
reject_button:
release_to_buyer_button:
released:
rep_name:
revenue:
revenue_last_year:
revenue_this_year:
sales_office:
salesperson:
save_and_release:
save_button:
save_changes_and_continue_button:
schedule_type:
search_button:
search_text_input:
select:
selected:
sellout_percent:
sent:
share:
share_goal:
show:
show_spot_allocations:
spot_no:
spot_option:
spot_rate:
spot_volume:
spots:
spots_missed:
spots_ordered:
start:
start_date:
station_action:
station_cpm:
station_cpp:
station_demographic:
station_notes:
station_order:
station_order_comment:
station_order_id:
station_order_no:
station_order_number:
station_rate:
station_rep_notes:
station_status:
stations:
status:
submit_button:
target_grp_goal:
time:
total_$$$:
total_cost:
total_preempted:
total_purchased_grps_impressions:
total_ratings:
total_revenue:
total_spots:
total_spots_ordered:
totals:
traffic_spots:
transfer_offer_button:
transfer_status:
transfer_to_mediaops_button:
type:
unit_rate:
units_available:
units_sold:
version:
videa_accept_rate:
videa_cpp:
videa_demographic:
videa_imp:
videa_impressions:
videa_need_goal:
videa_need_high:
videa_need_low:
videa_order:
videa_order_id:
videa_order_number:
videa_overall_aur:
videa_rate:
videa_rating:
videa_sell_through:
view_all:
view_offer:
view_order:
weekly_spots:
weeks_remaining:
year:
zero_dollar_spots:
