module.exports = [
  // { name: 'Async Computed', path: '/examples/async-computed', route: 'toast-example' },
  { name: 'Audio Player', path: '/examples/audio-player', route: 'audio-player-example' },
  { name: 'Avatar', path: '/examples/avatar', route: 'avatar-example' },
  // { name: 'Event Bus', path: '/examples/event-bus', route: 'toast-example' },
  // { name: 'Fetch Data', path: '/examples/fetch-data', route: 'toast-example' },
  // { name: 'Modal', path: '/examples/modal', route: 'toast-example' },
  // { name: 'Modals', path: '/examples/modals', route: 'toast-example' },
  // { name: 'Scoped Slots', path: '/examples/scoped-slots', route: 'sc-example' },
  { name: 'Banner', path: '/examples/banner', route: 'banner-example' },
  { name: 'Charts', path: '/examples/charts', route: 'charts-example' },
  { name: 'Devices', path: '/examples/devices', route: 'devices-example' },
  { name: 'Foundation', path: '/examples/foundation', route: 'foundation-example' },
  { name: 'Fraction Grid', path: '/examples/fraction-grid', route: 'fraction-grid-example' },
  { name: 'Modal 2', path: '/examples/modals/modal-2', route: 'modal-2-example' },
  { name: 'Multiselect', path: '/examples/multiselect', route: 'multiselect-example' },
  { name: 'Picture Input', path: '/examples/picture-input', route: 'picture-input-example' },
  { name: 'Select', path: '/examples/select', route: 'select-example' },
  { name: 'Select Checkbox', path: '/examples/select-checkbox', route: 'select-checkbox-example' },
  { name: 'Selectize', path: '/examples/selectize', route: 'selectize-example' },
  { name: 'Slider', path: '/examples/slider', route: 'slider' },
  { name: 'Table', path: '/examples/table', route: 'table-example' },
  { name: 'Toast', path: '/examples/toast', route: 'toast-example' },
  { name: 'Order By', path: '/examples/order-by', route: 'order-by-example' },
  { name: 'Windows', path: '/examples/windows', route: 'windows-example' },
  { name: 'Vue Grid Layout', path: '/examples/grids/vue-grid-layout', route: 'vue-grid-layout-example' },
  { name: 'Morehouse 1987', path: '/morehouse1987', route: 'morehouse1987' },
  // { name: 'Youtube Embed', path: '/examples/youtube-embed', route: 'toast-example' }
]
