module.exports = [
  // { name: 'Highchart', path: '/examples/charts/highchart', route: 'toast-example' },
  // { name: 'Async Computed', path: '/examples/async-computed', route: 'toast-example' },
  // { name: 'Audio Player', path: '/examples/audio-player', route: 'toast-example' },
  // { name: 'Avatar', path: '/examples/avatar', route: 'toast-example' },
  // { name: 'Event Bus', path: '/examples/event-bus', route: 'toast-example' },
  // { name: 'Fetch Data', path: '/examples/fetch-data', route: 'toast-example' },
  // { name: 'Modal', path: '/examples/modal', route: 'toast-example' },
  // { name: 'Modals', path: '/examples/modals', route: 'toast-example' },
  // { name: 'Scoped Slots', path: '/examples/scoped-slots', route: 'sc-example' },
  { name: 'Devices', path: '/examples/devices', route: 'devices-example' },
  { name: 'Banner', path: '/examples/banner', route: 'banner-example' },
  { name: 'Fraction Grid', path: '/examples/fraction-grid', route: 'fraction-grid-example' },
  { name: 'Select', path: '/examples/select', route: 'select-example' },
  { name: 'Selectize', path: '/examples/selectize', route: 'selectize-example' },
  { name: 'Table', path: '/examples/table', route: 'table-example' },
  { name: 'Toast', path: '/examples/toast', route: 'toast-example' },
  { name: 'Multiselect', path: '/examples/multiselect', route: 'multiselect-example' },
  { name: 'Order By', path: '/examples/order-by', route: 'order-by-example' },
  { name: 'Windows', path: '/examples/windows', route: 'windows-example' },
  { name: 'Morehouse 1987', path: '/morehouse1987', route: 'morehouse1987' },
  // { name: 'Youtube Embed', path: '/examples/youtube-embed', route: 'toast-example' }
]
