[
  {
    last_first: 'Nguyen, Huy The',
    title: 'Sr. Software Engineer',
    email: 'huy.nguyen@videa.tv',
    office: '678 645-6583',
    cell: '404 345-9173',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Noah, Brant',
    title: 'Project Manager',
    email: 'brant.noah@videa.tv',
    office: '678 645-6590',
    cell: '678 858-6263',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Ofoma, Chichi',
    title: 'QA Environment & Automation Manager',
    email: 'chichi.ofoma@videa.tv',
    office: '678 645-6453',
    cell: '404 425-9935',
    manager: 'Amorim, Rafael',
    secondary_approver: 'Kimber, Neil',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Paulet, Danielle',
    title: 'Sr. UX & Visual Designer',
    email: 'danielle.paulet@videa.tv',
    office: '678 645-6598',
    cell: '571 234-7476',
    manager: 'Greco, Phil',
    secondary_approver: 'Curtis, Ron',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Peyer, Jon',
    title: 'Executive Director of Technical Operations',
    email: 'jon.peyer@videa.tv',
    office: '678 645-4265',
    cell: '678-877-0687',
    manager: 'Catchpole, Lawrence',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Popescu, Andreea',
    title: 'Sr. Analytics Consultant',
    email: 'andreea.popescu@videa.tv',
    office: '678 645-6527',
    cell: '404-735-4342',
    manager: 'Smith, Brad',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Powers, Tom',
    title: 'Sr. Techical Writer ',
    email: 'tom.powers@videa.tv',
    office: '678 645-8533',
    cell: 'n/a',
    manager: 'Greco, Phil',
    secondary_approver: 'Curtis, Ron',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Purushothaman,Kris',
    title: 'Software Engineer',
    email: 'kris.purushothaman@videa.tv',
    office: '678-645-8115',
    cell: '770-289-5058',
    manager: 'Lingwood, Mei',
    secondary_approver: '',
    start_date:8    /31/2015
  },
  {
    last_first: 'Puthoff, David',
    title: 'Sr. Revenue Analyst',
    email: 'david.puthoff@videa.tv',
    office: '678-645-4288',
    cell: '513-314-0204',
    manager: 'Redding, Dee',
    secondary_approver: 'Whittaker, Maggie',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Redding, Deborah (Dee)',
    title: 'Revenue Manager',
    email: 'dee.redding@videa.tv',
    office: '678 645-6889',
    cell: '404 593-5097',
    manager: 'Whittaker, Maggie',
    secondary_approver: 'Smith, Brad',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Schoon, Chris',
    title: 'Enterprise Architect',
    email: 'chris.schoon@videa.tv',
    office: '678 645-6592',
    cell: '404-539-3970',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Sharp, Terry',
    title: 'Sr. Manager Technical Operations',
    email: 'terry.sharp@videa.tv',
    office: '678 645-6545',
    cell: '770 378-4192',
    manager: 'Peyer, Jon',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Skipper, Jennifer',
    title: 'Director Product Management',
    email: 'jennifer.skipper@videa.tv',
    office: '678 645-6547',
    cell: '205 585-3737',
    manager: 'Curtis, Ron',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Smith, Brad',
    title: 'SVP - Operations & Finance',
    email: 'brad.smith@videa.tv',
    office: '678 645-6552',
    cell: '646 270-7803',
    manager: 'Willliams, Shereta',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Smith,Holli',
    title: 'Sr. Usability Research Analyst',
    email: 'holli.smith@videa.tv',
    office: '678-645-7708',
    cell: '678-793-6162',
    manager: 'Greco, Phil',
    secondary_approver: '',
    start_date:8    /17/2015
  },
  {
    last_first: 'Stanley, Lee',
    title: 'Project Manager',
    email: 'lee.stanley@videa.tv',
    office: '678 645-6924',
    cell: '678 462-2189',
    manager: 'George, Gavin',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Starkey, Hesham',
    title: 'SQL Server Developer',
    email: 'hesham.starkey@videa.tv',
    office: '678 645-8352',
    cell: '410 610-4175',
    manager: 'Kimber, Neil',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Stephens, John',
    title: 'SQL Server Data Architect-Media Traffic',
    email: 'john.stephens@videa.tv',
    office: '678-645-8355',
    cell: '816 456-1306',
    manager: 'Kimber, Neil',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Tavoletti, Dawn',
    title: 'Sr. Product Manager',
    email: 'dawn.tavoletti@videa.tv',
    office: '678 645-6509',
    cell: '412-287-6480',
    manager: 'Smith, Brad',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Thompson, Jerome',
    title: 'Sr. UX & Visual Designer',
    email: 'jerome.thompson@videa.tv',
    office: '678 645-6581',
    cell: '404 791-4270',
    manager: 'Greco, Phil',
    secondary_approver: 'Curtis, Ron',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Tolbert, Victor',
    title: 'Sr. UI Architect & UX Designer',
    email: 'victor.tolbert@videa.tv',
    office: '678 645-6594',
    cell: '678 613-3400',
    manager: 'Greco, Phil',
    secondary_approver: 'Curtis, Ron',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Trizzino, Thomas',
    title: 'Sr. Software Engineer',
    email: 'tom.trizzino@videa.tv',
    office: '678 645-6596',
    cell: '404-931-8313',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Unuigbe, Osen',
    title: 'QA Engineer',
    email: 'unuigbe.osen@videa.tv',
    office: '678 645-6508',
    cell: '678 508-6473',
    manager: 'Amorim, Rafael',
    secondary_approver: 'Kimber, Neil',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Valentine, Janna',
    title: 'Broadcast Media/Buyer Advisor',
    email: 'janna.valentine@videa.tv',
    office: '678 645-8592',
    cell: '404 291-0079',
    manager: 'Davis, Brian',
    secondary_approver: 'Smith, Brad',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Vamadevan, David',
    title: 'Sr. Database Administrator ',
    email: 'david.vamadevan@videa.tv',
    office: '678 645-6597',
    cell: '646-708-4227',
    manager: 'Neil Kimber',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Venkatakrishna,Shivakumar',
    title: 'Manager, Software Development',
    email: 'shivakumar.venkatakrishna@videa.tv',
    office: '678-645-7707',
    cell: 'n\a',
    manager: 'Kimber, Neil',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Vetter, Daniel',
    title: 'Jr. .Net Software Engineer',
    email: 'daniel.vetter@videa.tv',
    office: '678-645-8593',
    cell: '770 877-1870',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Voin, Konstantin',
    title: 'Software Architect',
    email: 'konstantin.voin@videa.tv',
    office: '678-645-7260',
    cell: '678 575-0757',
    manager: 'Schoon, Chris',
    secondary_approver: 'Kimber, Neil',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Wai, CN',
    title: 'Revenue Management Specialist',
    email: 'cn.wai@videa.tv',
    office: '678 645-6611',
    cell: '',
    manager: 'Kimber, Neil',
    secondary_approver: 'Catchpole, Lawrence',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Wenz Pu-Folkes,Kelly',
    title: 'Sr. Director, Client Services',
    email: 'kelly.wenz@videa.tv',
    office: '678 645-8914',
    cell: '917 992-7198',
    manager: 'Gianunzio, Archie',
    secondary_approver: 'Smith, Brad',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Whittaker, Maggie',
    title: 'Senior Revenue Manager',
    email: 'maggie.whittaker@videa.tv',
    office: '678 645-4334',
    cell: '404 909-3732',
    manager: 'Smith, Brad',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Williams, Shereta',
    title: 'President',
    email: 'shereta.williams@videa.tv',
    office: '678 645-4165',
    cell: '404 550-4009',
    manager: '',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Wilson, Craig',
    title: 'Sr. Product Manager',
    email: 'craig.wilson@videa.tv',
    office: '678 645-6555',
    cell: '678 358-7723',
    manager: 'Curtis, Ron',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Womack, Kara',
    title: 'Sr. Director, Product Mgmt-Digital',
    email: 'kara.womack@videa.tv',
    office: '678-645-4079',
    cell: '678-596-5272',
    manager: 'Curtis, Ron',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Xiao,Wen',
    title: 'Software Engineer',
    email: 'wen.xiao@videa.tv',
    office: '678-645-6887',
    cell: '404-483-1238',
    manager: 'Liu,Yong',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: 'Zhu,Ling',
    title: 'Sofware Engineer',
    email: 'ling.zhu@videa.tv',
    office: '678-645-9106',
    cell: '404-949-0655',
    manager: 'Liu,Yong',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  },
  {
    last_first: '',
    title: '',
    email: '',
    office: '',
    cell: '',
    manager: '',
    secondary_approver: '',
    start_date: null,
    role_id: 1,
    organization_id: 1,
    skype_id: null
  }
]
